version: '3'

services:
  ## PHP-Apache service
  server:
    build:
      context: ./docker/server
    container_name: johnsons-webserver
    ports:
      - 80:80
    restart: always
    volumes:
      - ./htdocs:/var/www/html
    env_file:
      - ./docker/docker.env
    networks:
      - johnsons

  ## Mariadb service 
  database:
    image: mariadb:10.4.2
    container_name: johnsons-database
    restart: always
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - johnsons_data:/var/lib/mysql
    env_file:
      - ./docker/docker.env
    networks:
      - johnsons

  ## PhpMyAdmin
  myadmin:
    image: phpmyadmin/phpmyadmin:4.8.1
    container_name: johnsons-phpmyadmin
    ports:
      - 8081:80
    restart: always
    env_file:
      - ./docker/docker.env
    depends_on:
      - database
    networks:
      - johnsons

networks:
  johnsons:

volumes:
  johnsons_data:
